const names = {
  GetStarted: "Get Started",
  Onboarding: "Onboarding",
  Login: "Login",
  Code: "Code",
  Created: "Created",
  Register: "Register",
  RegisterConfirm: "RegisterConfirmation",
  Phone: "Phone",
  NewPass: "NewPass",
  ResetPass: "ResetPass",
  Track: "Track",
  Checkout: "Checkout",
  Failed: "Failed",
  Successful: "Successful",
  History: "History",
  Quality: "Quality",
  Reviews: "Reviews",
  Discount: "Discount",
  Product: "Product",
  Filter: "Filter",
  Shop: "Shop",
  ForgotPass: "ForgotPass",
  Phone: "Phone",
  ResetPass: "ResetPass",
  Method: "Method",
  NewCard: "NewCard",
  Address: "Address",
  NewAddress: "NewAddress",
  // Shipping: "Shipping",
  EditProfile: "EditProfile",
  TabNavigator: "TabNavigator",
  OrderSummary: "OrderSummary",
  Payment: "Payment",
  //Category: "Categories",
  UniversityScreen: "University",
  BrandsScreen: "Brands",
  ShopFilter:'ShopFilter',
  DiscountCodeScreen:'DiscountCodeScreen',
  Wishlist: "Wishlist",
  totalDiscount:"totalDiscount",
  discountDetail:"discountDetail",
  privacyPolicy:'PrivacyPolicy',
  termsCond:'Terms&Cond',
 changePassword:'ChangePassword',
 verifyPass: 'VerifyPass',
 review:"Review",
 giveReview:"GiveReview",
 viewReview:"ViewReview",
 offerList:"OfferList",
 contactUs:'ContactUs'

};

const tabNames = {
  Home: "Home",
  Category:"Categories",
  Search: "Search",
  Order: "Order",
  // Wishlist: "Wishlist",
  Profile: "Profile",
  
};

export {names, tabNames};
